Добавил API для платёжных шлюзов (#15)
fire-squad/autodonate pull request #16
Opened 2022-02-20 20:03 UTC by cofob

Resolves #15

2022-02-20 21:03 UTC, PerchunPak requested changes
Исправь для начала, пожалуйста, создание документации.
```
/autodonate/checkouts/16/autodonate/lib/payment/models.py:docstring of autodonate.lib.payment.models.PaymentService.pinging:1: WARNING: duplicate object description of autodonate.lib.payment.models.PaymentService.pinging, other instance in modules/autodonate.lib.payment.models, use :noindex: for one of them
/autodonate/checkouts/16/autodonate/lib/payment/models.py:docstring of autodonate.lib.payment.models.PaymentService.ping_interval:1: WARNING: duplicate object description of autodonate.lib.payment.models.PaymentService.ping_interval, other instance in modules/autodonate.lib.payment.models, use :noindex: for one of them
/autodonate/checkouts/16/autodonate/lib/payment/models.py:docstring of autodonate.lib.payment.models.PaymentService.logo_path:1: WARNING: duplicate object description of autodonate.lib.payment.models.PaymentService.logo_path, other instance in modules/autodonate.lib.payment.models, use :noindex: for one of them
/autodonate/checkouts/16/autodonate/lib/payment/models.py:docstring of autodonate.lib.payment.models.PaymentService.name:1: WARNING: duplicate object description of autodonate.lib.payment.models.PaymentService.name, other instance in modules/autodonate.lib.payment.models, use :noindex: for one of them
```

2022-02-21 10:30 UTC, cofob commented
@PerchunPak проблема доков не моя проблема, что они пытаются 2 раза заиндексить одно и то же. Они собираются, что ещё не хватает?

2022-02-21 10:49 UTC, PerchunPak requested changes
Посмотрел на ошибки сборки документации, и решил не дожидаться твоего фикса, так как исправления почти не повлияют на код.

2022-02-21 10:49 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +            raise Http404
Сделай пожалуйста описания для ошибок. Пример:
```py
raise Http404("HttpRequest.GET.get('id') not valid")
```

2022-02-21 10:49 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +            except Payment.DoesNotExist:
Перемести пожалуйста в отдельный класс с суффиксом/префиксом `Error`.

2022-02-21 10:49 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Как абстрактный метод может быть не обязательным? Как клиент узнает что этот метод не делает ничего, так как `Chield` не пере объявил его?
Тот же самый вопрос ко всем необязательным абстрактным методам.

2022-02-21 10:49 UTC, PerchunPak commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Sphinx (модуль для генерации документации) автоматически документирует переменные объявленные таки образом.
![image](https://user-images.githubusercontent.com/68118654/154938336-1710c1bd-7639-408f-b6ac-c405cde6b4eb.png)
Перепиши такие участки в стандартный `__init__` метод. И не забывай документировать атрибуты!

2022-02-21 10:49 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
Почему только рубли? Может лучше цикл `for`?

2022-02-21 10:49 UTC, PerchunPak commented on autodonate/models.py
> +    currency = SmallIntegerField(choices=[(i.name, i.value) for i in Currency], null=True)
Мне кажется, ты перепутал порядок. Разве не должно быть `(ID, NAME)`, когда ты написал наоборот.

Раньше:
```py
(0, "RUB")
```
Теперь:
```py
>>> (i.name, i.value)
("RUB", 0)
```

2022-02-21 10:52 UTC, cofob commented on autodonate/lib/payment/models.py
> +            raise Http404
Не знаю насколько с ними Django работает, но по идее должен. Да и если он будет отображать ошибку конечному пользователю то это косяк.

2022-02-21 10:52 UTC, cofob commented on autodonate/lib/payment/models.py
> +            except Payment.DoesNotExist:
Кого переместить 👀

2022-02-21 10:52 UTC, cofob commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Я потом сделаю 2 новых класса для разных типов шлюзов

2022-02-21 10:53 UTC, cofob commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Не понял что и куда переписать.

2022-02-21 10:53 UTC, cofob commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
Потому что Qiwi

2022-02-21 10:53 UTC, cofob commented on autodonate/models.py
> +    currency = SmallIntegerField(choices=[(i.name, i.value) for i in Currency], null=True)
Ага, надо подправить.

2022-02-21 10:54 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +            raise Http404
Будет. Если плагин не делает блока `try-except`.

2022-02-21 10:54 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +            except Payment.DoesNotExist:
`Payment.DoesNotExist`

2022-02-21 10:55 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Отметить пожалуйста это с помощью TODO коментария

2022-02-21 10:55 UTC, cofob commented on autodonate/lib/payment/models.py
> +            raise Http404
Он не должен давать пользователю болье информации чем положено. Это надо тестировать.

2022-02-21 10:55 UTC, cofob commented on autodonate/lib/payment/models.py
> +            except Payment.DoesNotExist:
Это встроенный метод для каждой модели, как я тебе его перенесу?

2022-02-21 10:57 UTC, PerchunPak commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Запись атрибутов в `__init__` метод.
Правильно:
```py
class A:
    def __init__(self):
        self.a = "a"
        self.b = "b"
```
Как ты делаешь:
```py
class A:
    a = "a"
    b = "b"
```

2022-02-21 10:58 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
Класс QiwiPayment реализован в плагине, не в основном плагине. Пусть плагины переопределяют сами валюты, если они не могут использовать все.

2022-02-21 10:59 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +            raise Http404
Это будет ошибка плагина, не наша.

2022-02-21 11:00 UTC, cofob commented on autodonate/lib/payment/models.py
> +            raise Http404
Это именно наша ошибка, мы её вызываем. Про какой `try-except` у плагинов ты говоришь, не пойму.

2022-02-21 11:01 UTC, cofob commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
<!--- TODO: тудурудурурдуруру --->
TODO: Новые классы

2022-02-21 11:01 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +            except Payment.DoesNotExist:
Понял.

2022-02-21 11:02 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Нет. В коде.

2022-02-21 11:04 UTC, cofob commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
Извиняюсь, ступил сначала. Это стандартное значение, которое плагин позже обязан заменить. Т.к. проект больше ориентирован на русскоговорящих (в большинстве - русские) то и валюта по-умолчанию - рубли. Можно не давать никакого значения, чтобы оно стало обязательным.

2022-02-21 11:06 UTC, cofob commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
TODO: Поставить флаг [unique](https://docs.python.org/3/library/enum.html#enum.unique)

2022-02-21 11:07 UTC, cofob commented on autodonate/lib/payment/models.py
> +            raise Http404
Плагин не должен перехватывать этой ошибки. Мы просто отсееваем до него невозможные значения.

2022-02-21 11:07 UTC, cofob commented on autodonate/lib/payment/models.py
> +            raise Http404
Её увидит сам Django и покажет стандартную 404 страницу.

2022-02-21 11:19 UTC, PerchunPak commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Смог исправить в b799cdbde62e20e7c1d8528bb44f084a98e75053.
![image](https://user-images.githubusercontent.com/68118654/154945279-57a1d5b7-3e5d-4a7e-8444-6b1f86f47caf.png)

2022-02-21 11:19 UTC, PerchunPak commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Но в классах где документация этого не требует, лучше сделать через `__init__`.

2022-02-21 11:32 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +            raise Http404
Даже если добавить описание ошибке?

2022-02-21 11:35 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
Еще лучше было бы добавить API для добавления своих валют. Да и плагин (мне кажется) должен сам поддерживает все валюты, не зависимо от нашей аудитории.

2022-02-22 01:36 UTC, cofob commented
@PerchunPak удали те файлы на которые жалуется дока из индекса

2022-02-22 01:37 UTC, cofob commented
И вообще это очень странно, откуда он там нашел `modules/`

2022-02-22 04:55 UTC, cofob commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
Он сам и поддерживает, это просто значение по-умолчанию. Добавить все валюты в currencies можно и ручками, чтобы плагин не заботился об этом позже, но у нас ограничение в 256 (или от 0128 до 128, смотря как база данных обрабатывает, signed или unsigned int) валют.

2022-02-22 04:58 UTC, cofob commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Разрешено в [197b8dc8](https://github.com/fire-squad/autodonate/commit/197b8dc8f73dae2032d22cb647ac24ee69464dc3)

2022-02-22 05:07 UTC, cofob commented on autodonate/lib/payment/models.py
> +            raise Http404
Разрешено в 1b1515208681550e1437bc802436423343f7ff47

2022-02-22 05:07 UTC, cofob commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Разрешено в 80efe01de6095d06f66211dedd4984455f767ccd

2022-02-22 05:08 UTC, cofob commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
И пока что не особо ясно как плагин сможет добавить новую валюту в этот enum. Да и нужно ли?

2022-02-22 05:08 UTC, cofob commented on autodonate/models.py
> +    currency = SmallIntegerField(choices=[(i.name, i.value) for i in Currency], null=True)
Разрешено в 68e5f9a7083c4e105b19f174918a00e14f6aacaa

2022-02-22 05:14 UTC, cofob commented on autodonate/lib/payment/models.py
> +    currencies: tuple[Currency] = (Currency.RUB,)
> Почему только рубли? Может лучше цикл `for`?

Разрешил в ea6123c064cecdbaa1d98aa8e72cca12df293eff

2022-02-22 07:57 UTC, PerchunPak commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Не решено, как я отметил в самом первом комментарии, это относиться и к другим 4 предупреждениям из за которых документация проваливается

2022-02-22 08:06 UTC, PerchunPak commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
И если отменить b799cdbde62e20e7c1d8528bb44f084a98e75053 это вернет ошибку, декоратор `unique` не помог.

2022-02-22 08:14 UTC, cofob commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
> И если отменить b799cdbde62e20e7c1d8528bb44f084a98e75053 это вернет ошибку, декоратор `unique` не помог.

unique нужен для предотвращения ошибок в базе данных. Он и не должен был решить проблему с доками.

2022-02-22 08:21 UTC, PerchunPak requested changes

2022-02-22 08:21 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Метод с декораторам `abstractmethod` должен быть обязательно переобъявлен.

2022-02-22 08:21 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +        name: Payment service name (like: "Qiwi").
Атрибуты больше не совпадают с объявленными.

2022-02-22 08:23 UTC, cofob commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Да. И?

2022-02-22 08:23 UTC, cofob commented on autodonate/lib/payment/models.py
> +        name: Payment service name (like: "Qiwi").
Да, нужно пофиксить.

2022-02-22 08:44 UTC, PerchunPak commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
Тогда почему ты написал что решил?

2022-02-22 08:45 UTC, PerchunPak commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
А в doc строке написано "Optional".

2022-02-22 08:46 UTC, cofob commented on autodonate/lib/payment/currencies.py
> +    EUR = 3
> Тогда почему ты написал что решил?

Потому что там был коммент с todo)

2022-02-22 09:13 UTC, cofob commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
А, ты про это. Да, надо дописать.

2022-02-22 13:11 UTC, cofob commented on autodonate/lib/payment/models.py
> +        """Optional abstract method for pinging payment service and getting updates from them.
Разрешено в 9fc7ec461379cf89ac612f1d9965b280fe7a6953

2022-02-22 13:11 UTC, cofob commented on autodonate/lib/payment/models.py
> +        name: Payment service name (like: "Qiwi").
Разрешено в 9fc7ec461379cf89ac612f1d9965b280fe7a6953

2022-02-22 14:01 UTC, PerchunPak approved these changes

2022-02-22 14:12 UTC, merged