Add make docker command
fire-squad/autodonate pull request #29
Opened 2022-03-03 13:44 UTC by cofob

2022-03-03 16:16 UTC, PerchunPak requested changes

2022-03-03 16:16 UTC, PerchunPak commented on Makefile
> +	docker build -t autodonate .
Сделай `fire-squad/autodonate`, или куда там заливается докер

2022-03-03 16:26 UTC, cofob commented on Makefile
> +	docker build -t autodonate .
Накуй? Потом делаешь `docker tag autodonate нужный-тэг`

2022-03-03 16:38 UTC, PerchunPak requested changes

2022-03-03 16:38 UTC, PerchunPak commented on Makefile
> +	docker build -t autodonate .
Замени пожалуйста на `poetry run docker build -t autodonate .`. И поставь его выше test, пожалуйста.

2022-03-03 17:02 UTC, cofob commented on Makefile
> +	docker build -t autodonate .
Зачем добавлять poetry run?

2022-03-03 17:24 UTC, PerchunPak commented on Makefile
> +	docker build -t autodonate .
`poetry run` использует команду в виртуальной среде проекта. Иногда оно может автоматически не подсасываться и будет примерно такое:
```
~/docs $ make html
/data/data/com.termux/files/usr/bin/sh: 1: sphinx-build: not found
make: *** [Makefile:20: html] Error 127
~/docs $ poetry run make html
Running Sphinx v4.4.0
```
А на счет докера, лучше перестраховаться и в env запускать, чем просто.

2022-03-04 10:39 UTC, PerchunPak approved these changes

2022-03-04 10:41 UTC, merged