Port logger from django branch :truck:
fire-squad/autodonate pull request #30
Opened 2022-03-03 14:02 UTC by cofob

2022-03-03 15:22 UTC, PerchunPak requested changes

2022-03-03 15:22 UTC, PerchunPak commented on autodonate/app.py
> +from autodonate import get_logger
`autodonate` это папка. Ты уверен что написал все правильно?
И подобный импорт есть в `__init__.py`

2022-03-03 15:22 UTC, PerchunPak commented on autodonate/logger/__init__.py
> +from autodonate.logger.logger import get_logger
Уверен что так можно, и не будет цикличного импорта?

2022-03-03 15:22 UTC, PerchunPak commented on autodonate/logger/logger.py
> +"""File to automatically create a logger for each file."""
Зачем создавать папку под 1 файл?

2022-03-03 15:28 UTC, cofob commented on autodonate/logger/logger.py
> +"""File to automatically create a logger for each file."""
Можно переместить в `utils` подмодуль.

2022-03-03 15:29 UTC, cofob commented on autodonate/logger/__init__.py
> +from autodonate.logger.logger import get_logger
Ошибок никаких нет.

2022-03-03 18:45 UTC, PerchunPak requested changes
Нужно обсудить и решить что делать со стилем импортов в `__init__.py`, а так вроде бы все хорошо.

(но спагетти надо убрать)

2022-03-04 10:47 UTC, PerchunPak approved these changes

2022-03-04 10:47 UTC, merged