Path decorators
fire-squad/autodonate pull request #31
Opened 2022-03-03 15:08 UTC by cofob

- Port logger from django branch :truck:
- Add log levels
- Add path decorators
- Fix tests :white_check_mark:

2022-03-03 16:32 UTC, PerchunPak requested changes

2022-03-03 16:32 UTC, PerchunPak commented on autodonate/application.py
> +log = get_logger(__name__)
Давай в один файл на запуск пихать логи, никому не нужно разделение на каждый модуль.

2022-03-03 16:32 UTC, PerchunPak commented on autodonate/logger/logger.py
> +        logger.setLevel(INFO)
Это будет экономия байтов, но поменяй его все местами, потому что уровень логов "DEBUG" будет меньше всего встречаться, а INFO почти всегда.

2022-03-03 16:32 UTC, PerchunPak commented on autodonate/logger/logger.py
> +        filename="{0}{1}".format(str(path / name), ".log"),
Зачем ".log" добавлять через str.format если можно явно написать?

2022-03-03 16:32 UTC, PerchunPak commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
Очень много методов с одинаковым кодом. Как на счет просто передавать единственную изменяемую переменную в строке, или написать код который объявляет код вместо этого копи паста.

2022-03-03 17:05 UTC, cofob commented on autodonate/application.py
> +log = get_logger(__name__)
Это упрощает поиск логов. Можно сделать разделение по env переменной.

2022-03-03 17:06 UTC, cofob commented on autodonate/logger/logger.py
> +        logger.setLevel(INFO)
Не понял. INFO у нас по-умолчанию и в качестве запасного варианта.

2022-03-03 17:06 UTC, cofob commented on autodonate/logger/logger.py
> +        filename="{0}{1}".format(str(path / name), ".log"),
Да, следует поправить.

2022-03-03 17:08 UTC, cofob commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
Проблема в том что это разные методы. web.get, web.post и web.put например, как это сделать в один метод? Передавать тип в строке? Тогда запуск будет выглядеть некрасиво.

2022-03-03 17:24 UTC, PerchunPak commented on autodonate/application.py
> +log = get_logger(__name__)
Давай

2022-03-03 17:26 UTC, PerchunPak commented on autodonate/logger/logger.py
> +        logger.setLevel(INFO)
Я имею ввиду заменить на:
```py
    if log_level == "INFO":
        logger.setLevel(INFO)
    elif log_level == "CRITICAL":
        logger.setLevel(CRITICAL)
    else:
        logger.setLevel(DEBUG)
```
Тоесть поменять `INFO` и `DEBUG` местами чтобы if блок не уходил далеко каждый раз.

2022-03-03 17:28 UTC, PerchunPak commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
```py
web.use("get", ...)
```
Или написать код который объявит другой код который сейчас написан. Чтобы напрямую не было копипаста.

Не знаю как хорошо донести мысль, наверное надо в ГС.

2022-03-04 10:39 UTC, cofob commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
> ```python
> web.use("get", ...)
> ```
> 
> Или написать код который объявит другой код который сейчас написан. Чтобы напрямую не было копипаста.
> 
> Не знаю как хорошо донести мысль, наверное надо в ГС.

Не знаю где ты там увидел `web.use`
И передавать аргументы строками, когда есть `enum` - плохо.

2022-03-04 10:53 UTC, PerchunPak commented on autodonate/logger/logger.py
> +        logger.setLevel(INFO)
Что то не видно что не часто. Он же вызывается при импорте любого нашего модуля, для получения переменной `log`.

2022-03-04 10:55 UTC, PerchunPak commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
Ну тогда напиши код который объявит все эти функции, вместо того чтобы копипастить их.

2022-03-04 10:56 UTC, cofob commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
> Ну тогда напиши код который объявит все эти функции, вместо того чтобы копипастить их.

Встал вопрос: как? Ты вообще смотрел код? Там разные функции используются, как я их тебе напишу, чтобы все работало и без `eval`?

2022-03-05 10:36 UTC, PerchunPak commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
Смотрел, код отличается только несколькими использованиями названия функции, да и что не так с `eval`?

2022-03-05 11:36 UTC, PerchunPak commented on autodonate/url/decorators.py
> +def head(path: str, name: Union[None, str] = None):
Ладно. Я попробовал реализовать и понял что как минимум mypy не видит функции.

2022-03-05 11:37 UTC, PerchunPak requested changes
Пройдись по коду и добавь пожалуйста doc-строки.

2022-03-05 12:27 UTC, cofob commented on autodonate/logger/logger.py
> +        logger.setLevel(INFO)
Это инициализация, замедлит только запуск на какие то незаметные доли.

2022-03-05 12:27 UTC, cofob commented on autodonate/application.py
> +log = get_logger(__name__)
?

2022-03-05 12:28 UTC, cofob commented
> Пройдись по коду и добавь пожалуйста doc-строки.

Я не умею доки писать >_<

2022-03-05 12:38 UTC, PerchunPak commented on autodonate/application.py
> +log = get_logger(__name__)
Сделай разделение по env переменной.

2022-03-08 09:06 UTC, closed without merging