Add bug report and PR templates
fire-squad/autodonate pull request #35
Opened 2022-03-03 20:38 UTC by PerchunPak

Closes #34.

2022-03-03 23:08 UTC, cofob requested changes

2022-03-03 23:08 UTC, cofob commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: В репозитории и в интернете нету дубликата этой ошибки.
Не "нету", а "нет"

2022-03-04 10:37 UTC, PerchunPak commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - label: В репозитории и в интернете нету дубликата этой ошибки.
Исправил.

2022-03-04 10:45 UTC, cofob approved these changes

2022-03-04 10:50 UTC, merged