Port Config class from `master`
fire-squad/autodonate pull request #38
Opened 2022-03-04 20:56 UTC by PerchunPak

# Порт класса Config из ветки `master`

Просто портировал, по сути очень похоже на CTRL+C CTRL+V, но я убрал 2 класса и заменил их одним (зачем 2).

# Важный check-list

- [x] Я написал подробное описание моих изменений.
- [x] Я написал подробную причину моих изменений.
- [x] Я точно прочитал и использовал все пункты [этого списка](https://github.com/fire-squad/autodonate/blob/master/CONTRIBUTING.md#перед-началом-работы).
- [x] Я записал изменение в `CHANGELOG.md` и добавил номер PR туда.
- [x] Я запустил `make test` и с тех пор ничего не менял.

2022-03-04 22:56 UTC, cofob requested changes
Структура проекта с переходом у нас поменялась, больше нет огромного `settings.py` в виде свалки `global` переменных. Теперь для того чтобы обратиться к конфигу нам нужно заново инициализировать объект (соответственно заново проверять переменные, парсить конфиг). 
Нужно переписать код так, чтобы он либо кэшировал, либо не инициализировал сам, а было что то вроде метода `.setup()`
К тому же тут нет асинков.

2022-03-05 11:12 UTC, PerchunPak commented
Я если честно, не могу понять куда туда впихнуть async. Разве что просто дописать `async` ко всем функциям, но это асинхронность ради асинхронности.

2022-03-05 12:29 UTC, cofob commented
> Я если честно, не могу понять куда туда впихнуть async. Разве что просто дописать `async` ко всем функциям, но это асинхронность ради асинхронности.

Функции встанут в очередь, а не будут исполнены мгновенно. Разве не так?

2022-03-05 14:34 UTC, cofob approved these changes

2022-03-05 14:34 UTC, merged