Plugin API
fire-squad/autodonate pull request #43
Opened 2022-03-10 14:46 UTC by cofob

# Важный check-list

- [ ] Я написал подробное описание моих изменений.
- [ ] Я написал подробную причину моих изменений.
- [x] Я точно прочитал и использовал все пункты [этого списка](https://github.com/fire-squad/autodonate/blob/master/CONTRIBUTING.md#перед-началом-работы).
- [ ] Я записал изменение в `CHANGELOG.md` и добавил номер PR туда.
- [x] Я запустил `make test` и с тех пор ничего не менял.
- [x] Я кофоб.

2022-03-11 11:55 UTC, PerchunPak commented on .vscode/launch.json
> +            "args": ["run", "python", "manage.py", "runserver"],
У некоторых может быть `py`, `python3` или вообще абсолютный путь. Лучше просто это выделить в README и не прописывать в VCS никакие команды. Тем более это **только** для VS Code, например PyCharm не подойдет.

2022-03-11 12:33 UTC, cofob commented on .vscode/launch.json
> +            "args": ["run", "python", "manage.py", "runserver"],
> Тем более это только для VS Code, например PyCharm не подойдет.

Ты это [сам прописал](https://github.com/fire-squad/autodonate/blob/master/.gitignore#L251). Для IDEA-подобных IDE есть такая [строка.](https://github.com/fire-squad/autodonate/blob/master/.gitignore#L245)
Может лучше убрать эти строки, чтобы не было проблем в будущем?

> У некоторых может быть py, python3 или вообще абсолютный путь.

А у меня просто python и мне удобно так. Это чужие проблемы.

> Лучше просто это выделить в README и не прописывать в VCS никакие команды.

Никто не станет гуглить как подружить VCS с poetry, если мы это сделаем заранее и повысим удобство разработки.

2022-03-11 20:34 UTC, PerchunPak commented on .vscode/launch.json
> +            "args": ["run", "python", "manage.py", "runserver"],
> Ты это [сам прописал](https://github.com/fire-squad/autodonate/blob/master/.gitignore#L251). Для IDEA-подобных IDE есть такая [строка.](https://github.com/fire-squad/autodonate/blob/master/.gitignore#L245)
Может лучше убрать эти строки, чтобы не было проблем в будущем?

Не я это прописывал. Я взял с сайта готовый `.gitignore`, и он не плохо работает. Хочу так же заметить что части этого файла взяты с разных сайтов и людей, например `Python` часть почти полностью повторяет то что GitHub предлагают при создании.

> А у меня просто python и мне удобно так. Это чужие проблемы.

Почему это чужие? Люди не читают FAQ. Они не будут даже переводить ошибку, просто откроют баг репорт и скажут чтобы пофиксили. Если ты что то делаешь - рассчитывай это так, чтобы даже самый тупой все понял.

> Никто не станет гуглить как подружить VCS с poetry, если мы это сделаем заранее и повысим удобство разработки.

Никто не будет, но им это и не нужно будет. Если понадобиться - посмотрят как сделано в `Makefile` и найдут как привязать к их IDE.

2022-03-11 20:53 UTC, cofob commented on .vscode/launch.json
> +            "args": ["run", "python", "manage.py", "runserver"],
Да хоспаде, просто добавь этот файл в гитигнор.

2022-03-21 15:29 UTC, PerchunPak requested changes

2022-03-21 15:29 UTC, PerchunPak commented on autodonate/__init__.py
> +initialize_all()
Инициализация при импорте. Ты хочешь в тестах и доках сайт запускать что ли? Сделай файл `run.py` в папке с `README.md`.

2022-03-21 15:29 UTC, PerchunPak commented on autodonate/app.py
>  app = web.Application()
Очень надеюсь что это не запускает сайт.

2022-03-21 15:29 UTC, PerchunPak commented on autodonate/module/__init__.py
> +class ExamplePlugin(Plugin):
Тестовый код в проде....

2022-03-21 15:29 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                for name in [item for item in dir(plugins_module) if not item.startswith("__")]:
Приватные методы могут начинаться с одного `_`.

2022-03-21 15:29 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +        except ModuleNotFoundError as e:
Переименуй `e` в `exception`. Тоже самое ниже в этом же файле.

2022-03-21 15:29 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                # Some checking to help end developer
Зачем эти проверки? Напиши просто `Module {plugins_path} doesn't provides a 'Plugin' class or/and 'setup' function.`.

2022-03-21 15:43 UTC, cofob commented on autodonate/app.py
>  app = web.Application()
Сайт запускается при `manage.py run`

2022-03-21 15:44 UTC, cofob commented on autodonate/module/__init__.py
> +class ExamplePlugin(Plugin):
Это WIP PR

2022-03-21 15:44 UTC, cofob commented on autodonate/plugin_manager.py
> +                # Some checking to help end developer
> to help end developer

2022-03-21 15:45 UTC, cofob commented on autodonate/plugin_manager.py
> +                "Check your `pip freeze` output and config. (Error: %s)"
freeze же выполняет свою задачу. Чем list лучше?

2022-03-21 15:46 UTC, cofob commented on autodonate/plugin_models.py
> +        self.log = get_logger(self.__class__.__name__)
В других логгерах я поменял на классы, для читаемости и эстатичности

2022-03-21 15:46 UTC, cofob commented on autodonate/plugin_models.py
> +            >>> self.route.get(self.index_view, '')
Тут правильный код, я не знаю почему оно крашит

2022-03-21 15:47 UTC, cofob commented on autodonate/utils/config.py
> +        raise TypeError("No. You cant do what.")
А как ты предлагаешь делать изменения сразу в нескольких ветках и тестить всё это?

2022-03-21 15:48 UTC, cofob commented on autodonate/utils/config.py
> +        raise TypeError("No. You cant do what.")
К тому же я тут всё переделал с singleton. Теперь никаких глобал переменных.

2022-03-21 16:02 UTC, cofob commented on autodonate/plugin_manager.py
> +        except ModuleNotFoundError as e:
`e` довольно очевидное название, так же как и `i`.

2022-03-21 19:53 UTC, PerchunPak commented on autodonate/__init__.py
> +initialize_all()
Загружаются!?! Не легально. Исправляй.

2022-03-21 19:55 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                # Some checking to help end developer
Мне кажется по ошибке он поймет что не так, а нам меньше тестов писать.

2022-03-21 19:55 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                "Check your `pip freeze` output and config. (Error: %s)"
Понятнее. `freeze` еще загуглить надо.

2022-03-21 19:55 UTC, PerchunPak commented on autodonate/plugin_models.py
> +            config: Config instance
(((((((((((((

2022-03-21 19:57 UTC, PerchunPak commented on autodonate/plugin_models.py
> +        self.log = get_logger(self.__class__.__name__)
По файлам был перебор, а тут... У нас для каждого класса свой файл, зачем еще больше разделять? Хотя... это убирает инициализацию логгера при импорте.

2022-03-21 19:58 UTC, PerchunPak commented on autodonate/plugin_models.py
> +            >>> self.route.get(self.index_view, '')
Потому что `self` это не объявленная переменная, поменяй на `Plugin`.

2022-03-21 23:45 UTC, cofob commented on autodonate/plugin_manager.py
> +        except ModuleNotFoundError as e:
Если бы я был программистом...

2022-03-21 23:47 UTC, cofob commented on autodonate/plugin_models.py
> +        self.log = get_logger(self.__class__.__name__)
Да, да, давая всё в `__init__.py` хуячить!

2022-03-21 23:49 UTC, cofob commented on autodonate/utils/config.py
> +        raise TypeError("No. You cant do what.")
Нет глобала, есть объект который создаётся в начаое и передаётся всем другим классам.

2022-03-22 12:18 UTC, PerchunPak commented on autodonate/utils/config.py
> +        raise TypeError("No. You cant do what.")
В этой ветке такой функции еще нет. Верни пожалуйста как было чтобы случайно ничего не сломать в проде.

2022-03-22 20:26 UTC, PerchunPak commented on autodonate/plugin_models.py
> +            >>> self.route.get(self.index_view, '')
Решено в e72a98358ada9d049253712416a20e1cd9b8e776.

2022-03-22 20:26 UTC, PerchunPak commented on autodonate/utils/config.py
> +        raise TypeError("No. You cant do what.")
А, понял.

2022-03-22 20:27 UTC, PerchunPak commented on autodonate/__init__.py
> +initialize_all()
Исправлено [тут](https://github.com/fire-squad/autodonate/pull/43/commits/284e18a3ee9a0751d6a3d19bc1e7a7ea388e1555#diff-5e3eb28cbd12894fdd534bbe9cc6885845a50f30c2237e6995a368174c8dd125L8).

2022-03-22 20:33 UTC, PerchunPak requested changes

2022-03-22 20:33 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                if plugins_module.__api_version__ != 1:
TODO мне: переделать ifы в класс с цепочкой обработчиков [(паттерн `Цепочка обязанностей`)](https://refactoring.guru/ru/design-patterns/chain-of-responsibility)

2022-03-22 20:33 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +def initialize_all() -> None:
Переделай пожалуйста эту функцию в класс, для более легкого тестирования.

2022-03-23 19:58 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                for name in [item for item in dir(plugins_module) if not item.startswith("__")]:
Исправил в 3a6203a0435732ed8cc24775d2aa7ae7c0130a54.

2022-03-23 20:02 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                "Check your `pip freeze` output and config. (Error: %s)"
Решено в 199795a3f999aa30e32aacff17bb67fdb6971d48.

2022-03-23 20:11 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +                # Some checking to help end developer
Исправил в b70ae89264df8bc892cf02e756466061f7f8d611.

2022-03-23 21:07 UTC, PerchunPak commented on autodonate/plugin_manager.py
> +    for plugins_path in config["plugins"]:
Стоп, что? Мы же вроде договаривались использовать `pip` как плагин-менеджер, а не чтобы юзер клонировал каждый плагин и прописывал к нему путь.

2022-04-12 07:17 UTC, merged